theme = "jellybeans"

[editor]
rulers = [80]

[editor.auto-save]
focus-lost = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.file-picker]
hidden = false

[keys.normal]
"C-g" = ":w!"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
"C-g" = ["normal_mode", ":w!"]
"C-ret" = "open_below"
