theme = "jellybeans"

[editor]
rulers = [80]

[editor.file-picker]
hidden = false

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
